export const Data = [

        {
            id:1,
            name:"Milk",
            image:'/asset/milk.png'
        },
        {
            id:2,
            name:"Vegetable",
            image:'/asset/veg.png'
        },
        {
            id:3,
            name:"Meat",
            image:'/asset/meat.png'
        },
        {
            id:4,
            name:"Milk",
            image:'/asset/milk.png'
        },
        {
            id:5,
            name:"Milk",
            image:'/asset/milk.png'
        },
        {
            id:6,
            name:"Vegetable",
            image:'/asset/veg.png'
        },
        {
            id:7,
            name:"Milk",
            image:'/asset/milk.png'
        },
        {
            id:8,
            name:"Meat",
            image:'/asset/meat.png'
        },
        {
            id:9,
            name:"Vegetable",
            image:'/asset/veg.png'
        },
        {
            id:10,
            name:"Milk",
            image:'/asset/milk.png'
        },
        {
            id:11,
            name:"Vegetable",
            image:'/asset/veg.png'
        },
        {
            id:12,
            name:"Milk",
            image:'/asset/milk.png'
        },
        {
            id:13,
            name:"Milk",
            image:'/asset/milk.png'
        },
        {
            id:14,
            name:"Meat",
            image:'/asset/meat.png'
        },
        {
            id:15,
            name:"Meat",
            image:'/asset/meat.png'
        },
        {
            id:16,
            name:"Meat",
            image:'/asset/meat.png'
        },
        {
            id:17,
            name:"Meat",
            image:'/asset/meat.png'
        },
        {
            id:18,
            name:"Meat",
            image:'/asset/meat.png'
        },
        {
            id:19,
            name:"Meat",
            image:'/asset/meat.png'
        },
        {
            id:11,
            name:"Vegetable",
            image:'/asset/veg.png'
        },
        {
            id:11,
            name:"Vegetable",
            image:'/asset/veg.png'
        },
];